docs/WebSocketClient.md

Reverts theturtle32/WebSocket-Node#197
keepaliveGracePeriod is actually not relevant to the client. It's a server-only configuration option.

Revert "adding keepaliveGracePeriod option"

---

docs/WebSocketConnection.md
lib/WebSocketConnection.js

Following the advice in #205, this rather trivial pull adds a `ping` and a `pong` event. Both events in their handlers pass in the received binary data. The `ping` event additionally adds `cancel`: a function taking no arguments that prevents the default behavior of the `ping` handler.

Expose events to facilitate manual ping/pong handling and tracking

---

lib/browser.js

browserify-lite only recognizes require() statements outside of all braces.

Support for browserify-lite

---

vendor/FastBufferList.js

fix #223 - clear reference to last item in FastBufferList when emptied

---

lib/WebSocketConnection.js

Starting from version 6.0.0, node returns an error ("callback" argument must be a function) when using native keepalives because of setTimeout calling with null timer handler.

Keepalive timer handling fixed

---

lib/WebSocketClient.js

If the HTTP server responds with a non-101 status code include the status description in the error text.

Include HTTP status description in case of failure

---

lib/WebSocketClient.js

For our use case, we need to be able to set the Host header.
We are using a gateway that redirect to the right API based on the Host header.

let the possibility to set the Host header

---

lib/WebSocketConnection.js

Mitigate infinite loop for broken connections.
https://github.com/theturtle32/WebSocket-Node/issues/288

Patch for https://github.com/theturtle32/WebSocket-Node/issues/288

---

lib/browser.js

Now the exposed `w3cwebsocket` export mirrors the native WebSocket more closely.
I hit this bug when moving previously native code to use this wrapper, the server-sde code was fine,
but the client-side code failed because `WebSocket.OPEN` was `undefined`.

add readyState constants to browser `w3cwebsocket`

---

lib/BufferUtil.fallback.js
lib/WebSocketFrame.js

Support for the `noAssert` argument was removed for Node.js 10.x
and all input will be validated from now on nevertheless.
This removes all `noAssert` entries and fixes the possible overflow.
Refs: https://github.com/nodejs/node/pull/18395

fix: do not use `noAssert`

---

README.md

I've verified that Windows users need only the `windows-build-tools` package to compile `websocket`. Might be a nice addition for those on Windows, but feel free to close it if you'd rather not take the PR.
Thanks!

docs: Add windows-build-tools for Windows users

---

lib/browser.js

In webpack 4 (Angular 8) 
```
var _global = (function () {
return this;
})();
```
will return undefined causing "Cannot read property WebSocket of undefined". 
Resolves #287.

Fix Webpack global scope issue

---

package.json

@ibc 
It looks like `WebSocket-Node` does not depend on `gulp` at runtime
Moving `gulp@^4.0.2` to `devDependencies` which make the project(which use websocket) do not have to install `gulp@^4.0.2` 😄 
original change [here](https://github.com/theturtle32/WebSocket-Node/commit/3cb29e1041ecca0a9c21f809890204271900f6f6)

Move gulp back to dev dependency

---

src/bufferutil.cc
src/validation.cc

As described in the object, this set of patches enable the build compatibility against most recent releases of node.js/electron and the updated NAN APIs

adding compatibility with V8 release greater than v7.6 (node and electron engines)

---

lib/browser.js
package.json

Related to #360.
The [es5-ext/global][es5g] module is based on Mathias Bynens' [polyfill][poly] for [`globalThis`][gT]. It uses the same robust technique but is more conservative in that it does not add a `globalThis` property to the resolved object, i.e. `window` in a browser and `global` in Node. It also lacks the "old IE" fallback seen in a [demo][demo] of the original polyfill, but that is easily provided in this commit.
[es5g]: https://github.com/medikoo/es5-ext/blob/master/global.js
[poly]: https://mathiasbynens.be/notes/globalthis
[gT]: https://github.com/tc39/proposal-global
[demo]: https://mathiasbynens.be/demo/globalthis-ie

Use es5-ext/global as a more robust way to resolve browser's window object (global this)

---

lib/WebSocketServer.js

My use case involves several WebSocket servers on the same HTTP server that each care about specific path in URL (for instance, one handles `ws://localhost/ws1` and another `ws://localhost/ws2`).
In this scenario I do not want to reject request if it doesn't correspond to particular WebSocketServer's path. However, if I do not accept and do not reject request, it will be kept in memory even after original socket connection is closed entirely.
One workaround is to use `wsServer.handleRequestResolved(request);`, which is not a public API and not intuitive.
I decided that at least when socket is closed, request should be removed from memory.
BTW, I'd also like to see `request.ignore()` method that allows to clean memory earlier (without explicitly accepting or rejecting the whole …

Fix memory leak with multiple WebSocket servers on the same HTTP server

---

docs/WebSocketServer.md
lib/WebSocketRequest.js
lib/WebSocketServer.js

Hi there,
While using the library I noticed that some users were having the following error:
```
Invalid handshake URIError: URI malformed
2020-10-23T13:30:17:     at decodeURIComponent (<anonymous>)
2020-10-23T13:30:17:     at XXX/node_modules/websocket/lib/WebSocketRequest.js:242:20
```
I've tracked down this to `WebSocketServer.prototype.handleUpgrade` function. If for any reason the websocket contains a cookie that fails while calling `decodeURIComponent` in `WebSocketRequest.prototype.parseCookies`.
The the error is only available by looking at the process stdout which is a causes application observability problem as it's difficult to see how often this happens.
**This PR adds the following**
1. Expose readHandshake errors to main app by adding `upgradeError` event. 
2. Allow users …

Expose parse options flags to readHandshake phase

---

README.md

The README states that "All current browsers are fully supported", which is not technically true. As noted in the [docs](https://github.com/theturtle32/WebSocket-Node/blob/master/docs/W3CWebSocket.md#constructor)
> When running in a browser (for example by using browserify) the browser's native WebSocket implementation is used, and thus just the first and second arguments (requestUrl and requestedProtocols) are used (those allowed by the W3C WebSocket API).
As someone who was not familiar with this, I spent a lot of time trying to debug the inconsistencies with the library between Node and the Browser. 
Even better would be if there were a way to throw an error when someone tries to pass headers, etc. into the W3C client from the browser.

Add W3C Caveat to Browser Support Info

---

package.json

1. Veracode platform identifies a high-level vulnerability in the dependency package es5-ext (Dependency of WebSocket).
2. I encountered this issue while using WebSocket version 1.0.33, which relies on es5-ext version 0.10.62.
3. According to the npm WebSocket documentation, the latest version available is 1.0.34, released on April 14, 2021.
4. Upon installing the latest WebSocket version, 1.0.34, I discovered it still depends on es5-ext version 0.10.62.
5. To address this, I've updated es5-ext to version 0.10.63.
6. I kindly request the team to merge this PR to resolve the vulnerability issue.

Updated the package es5-ext from 0.10.50 to 0.10.63

---

lib/WebSocketRequest.js

- fix typo in cookie expiration validation error message
- `npm test` *(fails: `tape` not found)*

Fix cookie expiration validation typo

---

docs/WebSocketServer.md

- clarify that dropConnectionOnKeepaliveTimeout actually closes idle connections after the grace period
- `npm test` *(fails: `tape: not found`)*

Fix keepalive timeout docs
